name: Documentation
on:
  push:
    branches:
    - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
    - name: Checkout branch
      uses: actions/checkout@master
      with:
        ref: release
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Setup
      run: |
        python setup.py sdist
    - name: Commit
      run: |
        git config --local user.name "github-actions[bot]"
        git add --all
        git commit --all -m "Build"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: build
        force: true